_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 3
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
T_HORIZON:
    value: 200
board_size:
    value: 5
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
num_epochs:
    value: 10000
